// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDDOXbJPRXV4HJvP6Yi80b65F6lVUS6YIY",
    authDomain: "manajemen-kegiatan.firebaseapp.com",
    projectId: "manajemen-kegiatan",
    storageBucket: "manajemen-kegiatan.firebasestorage.app",
    messagingSenderId: "851657076418",
    appId: "1:851657076418:web:98089355fa63d6e63b555b",
    measurementId: "G-0K4S8S4FNT"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoduwrrXUW67dlH3oZ9fPB9smPC8c3vn8',
    appId: '1:851657076418:android:6e7e765191833b563b555b',
    messagingSenderId: '851657076418',
    projectId: 'manajemen-kegiatan',
    storageBucket: 'manajemen-kegiatan.firebasestorage.app',
  );
}
